language: csharp
solution: gatekeeper.sln
mono: none
dotnet: 2.1

jobs:
  include:
    - stage: "Tests"
      name: "xUnit Tests"
      script:
        - dotnet restore
        - dotnet test GatekeeperTest\GatekeeperTest.csproj

notifications:
    slack: sem5640-2018:ouuibb583SpjRvEHwhoXE8qe
