language: csharp
solution: gatekeeper.sln
mono: none
dotnet: 2.1

# Specify which branches can be built on PR merge
branches:
  only:
    - master
    - development

jobs:
  include:
    - stage: "Tests"
      name: "xUnit Tests"
      script:
        - dotnet restore
        - dotnet test GatekeeperTest/GatekeeperTest.csproj

notifications:
    slack: sem5640-2018:ouuibb583SpjRvEHwhoXE8qe
